config/routes.rb
Rails.application.routes.draw do
  devise_for :organizations, controllers: { sessions: "organizations/sessions" }
  devise_for :users, controllers: { sessions: "users/sessions" }
  root to: "pages#home"

  get "filter", to: "filter#show"
  post "filter/categories", to: "filter#categories"
  post "filter/sub_categories", to: "filter#sub_categories"
  post "filter/organizations", to: "filter#organizations"
  post "filter/reset", to: "filter#reset"

  resources :events do 
    resources :event_participants, only: :create
  end
  resources :organizations, except: [:new, :create]

  resources :donations, only: [:create, :show] do
    resources :payments, only: :new
  end

  resources :event_participants, only: :destroy

  mount StripeEvent::Engine, at: '/stripe-webhooks'
end

app/views/shared/_card_categorie.html.erb
  <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(https://raw.githubusercontent.com/lewagon/fullstack-images/master/uikit/breakfast.jpg)">
    <%= category.name %>
  </div>

app/views/shared/_filter_cookies_categories.html.erb
<%= simple_form_for :filter_categories, url: filter_categories_path do |f|%>
  <div class="top-organization">
    <h1 class="welcome"><%= 'Hello' %> <span class="blue-name"><%= current_user.first_name %></span><%= ". It's a pleasure to have you with us !" %></h1>
    <%= render "shared/user_photo" %>
  </div>
    <h2 class="top-organization"><%= "What do you care about ?" %></h2>
   <%= f.input :categories,
                legend_tag: false,
                collection: @categories,
                item_label_class: 'd-block',
                wrapper_html: { class: 'cards_category' },
                as: :check_boxes,
                include_hidden: false,
                input_html: { class: "d-none" },
                label_method: lambda { |category| render 'shared/card_category', category: category }
  %>
  <div class="sticky d-flex justify-content-center gap-3" data-controller="hide-button" data-action="scroll@window->hide-button#scrollDown">
      <%= link_to "Back", root_path, class:'submit-btn'%>
      <%= f.button :submit, 'Continue', class: "submit-btn" %>
  </div>
<% end %>

app/views/shared/_filter_cookies_organizations.html.erb
<%= simple_form_for :filter_organizations, url: donations_path do |f|%>
  <div class="top-organization d-flex justify-content-between">
    <h1 class="welcome"><%= "Available organizations" %></h1>
      <%= render "shared/user_photo" %>
  </div>

  <% @sub_categories.each do |sub_category| %>
    <h2 class="mt-4 boldy" style="font-size: 22px"><%= sub_category.name %></h2>
    <%= f.input :organization,
                legend_tag: false,
                collection: sub_category.organizations,
                item_label_class: 'd-block',
                wrapper_html: { class: 'cards_category' },
                as: :check_boxes,
                include_hidden: false,
                input_html: { class: "d-none" },
                label_method: lambda { |organization| render 'shared/organization', organization: organization, clickable: true}
      %>

  <% end %>
  <div class="sticky d-flex justify-content-center gap-3" data-controller="hide-button" data-action="scroll@window->hide-button#scrollDown">
    <%= link_to 'Back', filter_reset_path, data: {turbo_method: :post}, class: "submit-btn"%>
    <%= f.button :submit, 'Cart', class: "submit-btn"%>
  </div>
<% end %>

app/views/shared/_filter_cookies_subcategories.html.erb
<%= simple_form_for :filter_sub_categories, url: filter_sub_categories_path do |f|%>
  <div class="top-organization">
    <h1 class="welcome"><%= "Tell us more " %> <span class="blue-name"><%= current_user.first_name %></span></h1>
    <%= render "shared/user_photo" %>
  </div>
  <% @categories.each do |category| %>
    <h2 class="boldy" style='font-size: 22px'><%= category.name %></h2>
    <div class="scrollmenu">
      <%= f.input :sub_categories,
                  legend_tag: false,
                  collection: category.sub_categories,
                  # item_label_class: 'd-inline-block',
                  wrapper_html: { class: 'cards_subcategory' },
                  as: :check_boxes,
                  include_hidden: false,
                  input_html: { class: "d-none" },
                  label_method: lambda { |category| render 'shared/card_subcategory', category: category }
      %>
    </div>
  <% end %>
  <div class="sticky d-flex justify-content-center gap-3" data-controller="hide-button" data-action="scroll@window->hide-button#scrollDown">
    <%= link_to "Back", filter_reset_path, data: {turbo_method: :post}, class: "submit-btn"%>
    <%= f.button :submit, 'Continue', class: "submit-btn" %>
  </div>
<% end %>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>

app/views/shared/_form_events.html.erb
<div class="container login mt-4">
  <h1>Create your event</h1>

  <%= simple_form_for event, html: {data: {controller: "flatpickr"}} do |f| %>
    <%= f.input :name %>
    <%= f.input :description%>
    <%= f.input :address %>
    <%= f.input :photos, as: :file, input_html: { multiple: true } %>

    <%= f.input :start_date,label: false, as: :string,input_html: {
                                    class:"d-none",
                                data: {
                                  flatpickr_target: "startDate",
                                } }
                                %>
    <%= f.input :end_date, as: :string,label: false,
                                input_html: {
                                  class: "d-none",
                                  data: {
                                    flatpickr_target: 'endDate',
                                  } } %>
    <div class="d-flex justify-content-center gap-3">
      <%= link_to "Get back to index", events_path, class: "btn btn-danger "%>
      <%= f.submit class: "btn btn-danger" %>
    </div>
  <% end %>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon" data-controller="hide-button" data-action="scroll@window->hide-button#scrollNav">
  <div class="container-fluid d-flex justify-content-around">
    <%= link_to root_path, :action => 'go' do %>
      <div class="card-icon-title">
        <iconify-icon class="icons-home" icon="ant-design:home-filled" style="color: white;"></iconify-icon>
        <h5>Home</h5>
      </div>
    <% end %>

    <%= link_to events_path, :action => 'go' do %>
      <div class="card-icon-title">
          <iconify-icon class="icons-home" icon="material-symbols:event" style="color: white;"></iconify-icon>
          <h5>Events</h5>
      </div>
    <% end %>
  </div>
</div>

app/views/shared/_navbar_events.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon" data-controller="hide-button" data-action="scroll@window->hide-button#scrollNav">
  <div class="container-fluid d-flex justify-content-around">
    <%= link_to root_path, :action => 'go' do %>
      <div class="card-icon-title">
        <iconify-icon class="icons-home" icon="ant-design:home-filled" style="color: white;"></iconify-icon>
        <h5>Home</h5>
      </div>
    <% end %>
  </div>
</div>

app/views/shared/_navbar_orga.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon" data-controller="hide-button" data-action="scroll@window->hide-button#scrollNav">
  <div class="container-fluid d-flex justify-content-around">
    <%= link_to root_path, :action => 'go' do %>
      <div class="card-icon-title">
        <iconify-icon class="icons-home" icon="ant-design:home-filled" style="color: white;"></iconify-icon>
        <h5>Home</h5>
      </div>
    <% end %>

    <%= link_to events_path, :action => 'go' do %>
      <div class="card-icon-title">
          <iconify-icon class="icons-home" icon="material-symbols:event" style="color: white;"></iconify-icon>
          <h5>Events</h5>
      </div>
    <% end %>
  </div>
</div>

app/views/shared/_organization_new_payment.html.erb
<div class="card-organization-new-payment mt-4 mb-3" >
  <%= cl_image_tag organization.photo.key, crop: :fill if organization.photo.attached? %>
  <p> You have donated <strong><%= humanized_money_with_symbol orga_donas.price %></strong> to <%=organization.name %> 🙏🏻 </p>

  </div>

app/views/shared/_organization_photo.html.erb
<div>
    <ul class='img-dropdown'>
        <li class="dropdown">
            <% if current_organization.photo.attached? %>
                <%= cl_image_tag current_organization.photo.key,
                crop: :limit,
                class:"rounded-circle photo-user dropdwon-toggle",
                id:"imgDropdown",
                data: { bs_toggle: "dropdown", controller: "click-button", action: "click->click-button#highlightUser" },
                'aria-haspopup': true,
                'aria-expanded': false %>
            <% else %>
                <%= image_tag "icon-user.png", class:"rounded-circle photo-user dropdown-toggle", id:'imgDropdown', data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
            <% end %>
            <div class="dropdown-menu dropdown-menu-end smooth" aria-labelledby="imgDropdown">
                <%= link_to 'Settings', edit_organization_registration_path, class:'dropdown-item' %>
                <%= link_to "Log out", destroy_organization_session_path, data: {turbo_method: :delete}, class: "dropdown-item" %>
            </div>
        </li>
    </ul>
</div>

app/views/shared/_organization_show_payment.html.erb
<div class="card-organization-new-payment mt-4 mb-3" >
  <%= cl_image_tag organization.photo.key, crop: :fill if organization.photo.attached? %>
  <p> <%= organization.name%> thanks <%= current_user.first_name %> for his donation  🙏🏻 </p>

</div>

app/views/shared/_sub_categorie.html.erb
<div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(https://raw.githubusercontent.com/lewagon/fullstack-images/master/uikit/breakfast.jpg)">
    <%= SubCategory.all %>
  </div>
<%# <%= sub_category.name %> %>

app/views/shared/_user_photo.html.erb
<div>
    <ul class='img-dropdown'>
        <li class="dropdown">
            <% if current_user && current_user.photo.attached? %>
                <%= cl_image_tag current_user.photo.key,
                class:"rounded-circle photo-user dropdwon-toggle",
                id:"imgDropdown",
                data: { bs_toggle: "dropdown", controller: "click-button", action: "click->click-button#highlightUser" },
                'aria-haspopup': true,
                'aria-expanded': false %>
            <% elsif current_organization.photo.attached? %>
                <%= cl_image_tag current_organization.photo.key,
                    class:"rounded-circle photo-user dropdwon-toggle",
                    id:"imgDropdown",
                    data: { bs_toggle: "dropdown", controller: "click-button", action: "click->click-button#highlightUser" },
                    'aria-haspopup': true,
                    'aria-expanded': false %>
            <% else %>
                <%= image_tag "icon-user.png", class:"rounded-circle photo-user dropdown-toggle", id:'imgDropdown', data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
            <% end %>
            <div class="dropdown-menu dropdown-menu-end smooth" aria-labelledby="imgDropdown">
                <%= link_to 'Settings', edit_user_registration_path, class:'dropdown-item' %>
                <%= link_to "Log out", destroy_user_session_path, data: {turbo_method: :delete}, class: "dropdown-item" %>
            </div>
        </li>
    </ul>
</div>