config/routes.rb
Rails.application.routes.draw do
  devise_for :organizations, controllers: { sessions: "organizations/sessions" }
  devise_for :users, controllers: { sessions: "users/sessions" }
  root to: "pages#home"

  get "filter", to: "filter#show"
  post "filter/categories", to: "filter#categories"
  post "filter/sub_categories", to: "filter#sub_categories"
  post "filter/organizations", to: "filter#organizations"
  post "filter/reset", to: "filter#reset"

  resources :events do 
    resources :event_participants, only: :create
  end
  resources :organizations, except: [:new, :create]

  resources :donations, only: [:create, :show] do
    resources :payments, only: :new
  end

  resources :event_participants, only: :destroy

  mount StripeEvent::Engine, at: '/stripe-webhooks'
end

app/models/event.rb
class Event < ApplicationRecord
  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?

  has_many :event_participants, dependent: :destroy
  belongs_to :organization
  has_many_attached :photos
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_event, only: %I[show destroy edit update]
  skip_before_action :authenticate_user!, only: [:new, :create, :index]

  def index

    if current_user
      @logger = current_user
      @events = Event.near(current_user.address, 50, units: :km)
    elsif current_organization
      @logger = current_organization
      @events = current_organization.events
    else
      authenticate_user!
    end
  end

  def show
    set_event
  end

  def new
    @event = Event.new
  end

  def create
    @event = Event.new(params_events)
    @event.organization = current_organization
    if @event.save
      redirect_to events_path
    else
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
  end

  def edit
  end

  private

  def set_event
    @event = Event.find(params[:id])
  end

  def params_events
    params.require(:event).permit(:name, :description, :address, :start_date, :end_date, photos: [])
  end
end

app/views/events/destroy.html.erb
<h1>Events#destroy</h1>
<p>Find me in app/views/events/destroy.html.erb</p>

app/views/events/edit.html.erb
<h1>Events#edit</h1>
<p>Find me in app/views/events/edit.html.erb</p>

app/views/events/index.html.erb
<div class="top-organization">
    <h3><%= 'Events near you:' %></h3>
    <%= render "shared/user_photo" , current_user: @logger%>
</div>

<%# CARDS EVENTS %>

<% @events.each do |event| %>
    <div class="card-event">
        <%= cl_image_tag event.organization.photo.key %>
        <div class="event-bottom">
            <div id="event_<%= event.id %>" class="event-name-description">
                <div class="event-name-date">
                    <p style='margin: 0'><%= event.name %> - <%= event.organization.name %></p>
                    <p class="event-date"><iconify-icon icon="clarity:date-line"></iconify-icon><%=event.start_date %> / <%= event.end_date %></p>
                </div>
                <div class="event-description">
                    <p><%= event.description %></p>
                </div>
            </div>
            <div class="event-footer">
                <div class="event-address"><iconify-icon icon="akar-icons:location"></iconify-icon><%= event.address %></div>
                <% if current_user %>
                    <% if event.event_participants.where(user: current_user).empty? %>
                        <%= link_to "Going", event_event_participants_path(event), data: {turbo_method: "post"}, class: 'submit-btn event-footer-button'%>
                    <% else %>
                        <%= link_to "Not Going", event_participant_path(event.event_participants.find_by(user: current_user)), data: {turbo_method: "delete"}, class: 'submit-btn event-footer-button button-cancel' %>
                    <% end %>
                <% end %>
                <div class="event-participants"><iconify-icon icon="akar-icons:people-group"></iconify-icon><%= event.event_participants.count %></div>
            </div>
        </div>
    </div>
<% end %>
 <%= render "shared/navbar_events" %>

app/views/events/new.html.erb
<%= render "shared/form_events", event: @event%>

app/views/events/show.html.erb
<h1>Events#show</h1>
<p>Find me in app/views/events/show.html.erb</p>