config/routes.rb
Rails.application.routes.draw do
  devise_for :organizations, controllers: { sessions: "organizations/sessions" }
  devise_for :users, controllers: { sessions: "users/sessions" }
  root to: "pages#home"

  get "filter", to: "filter#show"
  post "filter/categories", to: "filter#categories"
  post "filter/sub_categories", to: "filter#sub_categories"
  post "filter/organizations", to: "filter#organizations"
  post "filter/reset", to: "filter#reset"

  resources :events do 
    resources :event_participants, only: :create
  end
  resources :organizations, except: [:new, :create]

  resources :donations, only: [:create, :show] do
    resources :payments, only: :new
  end

  resources :event_participants, only: :destroy

  mount StripeEvent::Engine, at: '/stripe-webhooks'
end

app/views/pages/home.html.erb
<div class="bg"></div>
<div class="container-home">
  <div class="scroll-home">
    <div class="container-homepage">
        <h1 class="home-title mt-4">Help Us</h1>
        <div class="home-bottom">
            <p class="home-description"><span data-controller="typed-js"></span></p>
            <div class="home-icon">
                <p>Swipe</p>
                <iconify-icon icon="bi:arrow-down-circle"></iconify-icon>
            </div>
        </div>
    </div>
    <div class="container-homepage">
        <div class="home-cards">
            <div class="donate-card">
                <div class="card-icon-title">
                    <iconify-icon class="icons-home" icon="bxs:donate-heart" style="color: white;"></iconify-icon>
                    <h2>Donate</h2>
                </div>
                <p>Thanks to Help Us, you can make a donation to help many associations</p>
                <%= link_to "Donate", filter_path, class:"btn btn-dark home-cards-button" %>
            </div>
            <div class="event-card">
                <div class="card-icon-title">
                    <iconify-icon class="icons-home" icon="material-symbols:event" style="color: white;"></iconify-icon>
                    <h2>Events</h2>
                </div>
                <p>See all events available around you and choose to partipate or not to each event</p>
                <%= link_to "Events", events_path, class:"btn btn-dark home-cards-button" %>

            </div>
            <div class="association-card">
                <iconify-icon class="icons-home" icon="simple-icons:worldhealthorganization" style="color: white"></iconify-icon>
                <h2>Organizations</h2>
                <p>Register your organization, share events and find benevolents and donators</p>
                <%= link_to "Organizations", organizations_path, class:"btn btn-dark home-cards-button" %>
            </div>
        </div>
    </div>
  </div>
</div>